# Generated by Django 5.2.6 on 2025-10-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='City',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='State',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Zipcode',
        ),
        migrations.AlterField(
            model_name='menu',
            name='Inventory',
            field=models.SmallIntegerField(max_length=5),
        ),
    ]
